// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiaesServer.Data;

#nullable disable

namespace SiaesServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231229204344_MigracionInicialModeloRegistrarUsuario")]
    partial class MigracionInicialModeloRegistrarUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiaesLibraryShared.Models.Model_Tanu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidosMadre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidosRecienNacido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentroDiagnosticoReferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimientoRecienNacido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPrimerTamizaje")
                        .HasColumnType("datetime2");

                    b.Property<string>("LateralidadDerechaGradoSordera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LateralidadDerechaTipoSordera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LateralidadIzquierdaGradoSordera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LateralidadIzquierdaTipoSordera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreHospital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMadre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRecienNacido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentificacionMadre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentificacionRecienNacido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PEAAV0_1")
                        .HasColumnType("bit");

                    b.Property<bool>("PEAAV0_2")
                        .HasColumnType("bit");

                    b.Property<bool>("PasaDerechoEOA")
                        .HasColumnType("bit");

                    b.Property<bool>("PasaIzquierdoEOA")
                        .HasColumnType("bit");

                    b.Property<string>("SexoRecienNacido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono1Madre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono2Madre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoracionDiagnostica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cuadro1_Tanu");
                });

            modelBuilder.Entity("SiaesLibraryShared.Models.UsuarioRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodEstablecimiento")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCaducidad")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegistrarUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
